### ISSUE TITLE
openai import issue

### ISSUE THREAD

**Issue by Panchajanya1999** [Dataherald/Assistant#2]
Installed requiremnts.txt

getting this.

```bash
Traceback (most recent call last):
  File "/home/panchajanya/Development/work/Assistant/test.py", line 1, in <module>
    from assistant import AIAssistant
  File "/home/panchajanya/Development/work/Assistant/assistant.py", line 2, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (/home/panchajanya/Development/work/Assistant/lib/python3.11/site-packages/openai/__init__.py)
```

I just created a custom retrieval chat function

```python
from assistant import AIAssistant

assistant = AIAssistant(
    instruction=""" You are a helpful agent that helps user with their question about LLMs.""",
    model="gpt-4-1106-preview",
    use_retrieval=True,
    )
file_id = assistant.upload_file("assistants_files/Mankind_v1.1.csv")
assistant.chat(file_ids=[file_id])
```

**Comment by Panchajanya1999** [comment]
This is what I get if I upgarde openai to 1.30

```python
Traceback (most recent call last):
  File "/home/panchajanya/Development/work/Assistant/test.py", line 1, in <module>
    from assistant import AIAssistant
  File "/home/panchajanya/Development/work/Assistant/assistant.py", line 6, in <module>
    from openai.types.beta.threads import Run, ThreadMessage
ImportError: cannot import name 'ThreadMessage' from 'openai.types.beta.threads' (/home/panchajanya/Development/work/Assistant/lib/python3.11/site-packages/openai/types/beta/threads/__init__.py)
```
